"""Initial migration

Revision ID: 7e2891dcd5d8
Revises: 
Create Date: 2026-07-25 22:24:03.115788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Time
from datetime import time


# revision identifiers, used by Alembic.
revision: str = '7e2891dcd5d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EMPLOYEE', 'ADMIN', name='userrole', native_enum=False),
               existing_nullable=False)


    rooms_table = table('rooms',
                        column('id', Integer),
                        column('name', String)
                        )

    slots_table = table('slots',
                        column('id', Integer),
                        column('room_id', Integer),
                        column('start_time', Time),
                        column('end_time', Time)
                        )

    op.bulk_insert(rooms_table, [
        {'id': 1, 'name': 'Переговорная Альфа'},
        {'id': 2, 'name': 'Переговорная Бета'}
    ])

    working_hours = [
        (time(9, 0), time(11, 0)),
        (time(11, 0), time(13, 0)),
        (time(14, 0), time(16, 0)),
        (time(16, 0), time(18, 0)),
    ]

    slots_data = []
    slot_id = 1
    for room_id in [1, 2]:
        for start, end in working_hours:
            slots_data.append({
                'id': slot_id,
                'room_id': room_id,
                'start_time': start,
                'end_time': end
            })
            slot_id += 1

    op.bulk_insert(slots_table, slots_data)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('EMPLOYEE', 'ADMIN', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
